-- EX1 --
select name from CITY
where COUNTRYCODE= "USA" AND population>120000

--EX2--
SELECT * FROM CITY
WHERE COUNTRYCODE = "JPN"

--EX3--
SELECT CITY, STATE FROM STATION

--EX4--
SELECT DISTINCT CITY FROM STATION 
WHERE (CITY LIKE "A%") 
    OR (CITY LIKE "E%")
    OR (CITY LIKE "I%")
    OR (CITY LIKE "O%")
    OR (CITY LIKE "U%")

--EX5--
SELECT DISTINCT CITY FROM STATION
WHERE (CITY LIKE "%A")
OR (CITY LIKE"%E")
OR (CITY LIKE "%I")
OR (CITY LIKE "%O")
OR (CITY LIKE "%U")
ORDER BY CITY

--EX6--
SELECT DISTINCT CITY FROM STATION
WHERE (CITY NOT LIKE "A%")
AND (CITY NOT LIKE "E%")
AND (CITY NOT LIKE "U%")
AND (CITY NOT LIKE "O%")
AND (CITY NOT LIKE "I%")
ORDER BY CITY

--EX7--
select name from employee
order by NAME

--EX8--
SELECT NAME FROM EMPLOYEE
WHERE SALARY>2000 AND MONTHS<10
ORDER BY EMPLOYEE_ID

--EX9--
SELECT PRODUCT_ID FROM PRODUCTS
WHERE LOW_FATS LIKE 'Y'
AND RECYCLABLE LIKE 'Y'
ORDER BY PRODUCT_ID

--EX10--
SELECT NAME FROM CUSTOMER
WHERE REFEREE_ID <>2 OR REFEREE_ID IS NULL

--EX11--
SELECT NAME, POPULATION, AREA FROM WORLD
WHERE (AREA >=3000000) OR (POPULATION>=25000000)

--EX12--
SELECT DISTINCT AUTHOR_ID AS ID FROM VIEWS
WHERE AUTHOR_ID=VIEWER_ID
ORDER BY AUTHOR_ID

--EX13--
SELECT DISTINCT part,  assembly_step FROM parts_assembly
WHERE finish_date IS NULL;

--EX14--
select * from lyft_drivers
WHERE (YEARLY_SALARY<=30000) OR (YEARLY_SALARY>=70000)

--EX15--
select ADVERTISING_CHANNEL from uber_advertising
WHERE MONEY_SPENT>100000
