// Builds Lily, the app's narrator, from the open-source ToonHead avatar set (design: Johan Melin, CC BY 4.0,
// via DiceBear, MIT). Output: one inline SVG whose mouth, eyes and eyebrows are swappable layers, so the app can
// animate talking, blinking and expressions with CSS.
// Run once (needs: npm i @dicebear/core @dicebear/collection):  node tools/build_lily.mjs
import { createAvatar } from '@dicebear/core';
import { toonHead } from '@dicebear/collection';
import fs from 'fs';

const LILY = { seed: 'Lily', hair: ['bun'], rearHair: ['longWavy'], hairColor: ['a55728'], skinColor: ['f1c3a5'], clothes: ['dress'], clothesColor: ['eab308'], beardProbability: 0, eyes: ['happy'], eyebrows: ['happy'], mouth: ['smile'] };
const PARTS = { mouth: ['smile', 'agape', 'laugh', 'sad'], eyes: ['happy', 'bow', 'wide', 'wink'], eyebrows: ['happy', 'raised', 'sad'] };

// tokenise into tags/text so we can diff variants without ever cutting a tag in half
const tokens = svg => svg.replace(/<metadata[\s\S]*?<\/metadata>/, '').match(/<[^>]+>|[^<]+/g);
const balanced = t => { let d = 0; for (const x of t) { if (/^<\//.test(x)) d--; else if (/^<[^!?][^>]*[^/]>$/.test(x) || /^<[a-z]+>$/i.test(x)) d++; if (d < 0) return false; } return d === 0; };
const render = o => createAvatar(toonHead, o).toString();
const base = tokens(render(LILY));

const ranges = {};
for (const [part, vals] of Object.entries(PARTS)) {
  const vs = vals.map(v => { const t = tokens(render({ ...LILY, [part]: [v] })); let p = 0; while (p < base.length && t[p] === base[p]) p++; let s = 0; while (s < base.length - p && t[t.length - 1 - s] === base[base.length - 1 - s]) s++; return { v, t, p, s }; });
  const diff = vs.filter(x => x.p < base.length || x.t.length !== base.length);
  let lo = Math.min(...diff.map(x => x.p)), hi = Math.max(...diff.map(x => base.length - x.s));
  // widen until every layer is a well-formed fragment
  const layer = (x, lo, hi) => x.t.slice(lo, x.t.length - (base.length - hi));
  while (!vs.every(x => balanced(layer(x, lo, hi))) && lo > 0) { lo--; hi++; }
  ranges[part] = { lo, hi, layers: Object.fromEntries(vs.map(x => [x.v, layer(x, lo, hi)])) };
}
const order = Object.entries(ranges).sort((a, b) => a[1].lo - b[1].lo);
for (let k = 1; k < order.length; k++) if (order[k][1].lo < order[k - 1][1].hi) throw new Error('overlapping parts');
let body = '', i = 0;
for (const [part, r] of order) {
  body += base.slice(i, r.lo).join('');
  for (const [v, els] of Object.entries(r.layers)) body += `<g class="ly ly-${({ mouth: "m", eyes: "e", eyebrows: "b" })[part]}-${v}">${els.join('')}</g>`;
  i = r.hi;
}
body += base.slice(i).join('');
const svg = body.replace('<svg ', '<svg class="lily-svg" aria-hidden="true" ');
const out = `// Generated by tools/build_lily.mjs. Lily = ToonHead avatar by Johan Melin (CC BY 4.0), rendered with DiceBear (MIT).
export const LILY_SVG = ${JSON.stringify(svg)};
`;
fs.writeFileSync(new URL('../docs/js/reels/lily-svg.js', import.meta.url), out);
// a plain picture of Lily (default face) for lesson speech boxes
fs.writeFileSync(new URL('../docs/icons/lily.svg', import.meta.url), render(LILY).replace(/<metadata[\s\S]*?<\/metadata>/, ''));
console.log('parts', order.map(([p, r]) => `${p}[${r.lo},${r.hi})`).join(' '), 'bytes', svg.length);
